### ISSUE TITLE
Elixir / Phoenix

### ISSUE THREAD

**Issue by nucleartide** [nucleartide/ideas#6]
It'd be cool to try Elixir for @cross311's weekly coding challenges. 😄

**Comment by nucleartide** [comment]
Some things to do:

1. [ ] Compare productivity to that of Ember + Ember CLI. Can I rapidly develop side projects in this?
2. [ ] Investigate Elixir's community.

Also if I recall, @poteto is a big Elixir proponent (hi if you see this! 👋 ).

**Comment by cross311** [comment]
hi

**Comment by nucleartide** [comment]
oh hi
